/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.RoadUserChargingConfigMessage;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.asn.j2735.r2024.RoadSafetyMessage.EventRecurrence;
import us.dot.its.jpo.asn.j2735.r2024.TollAdvertisementMessage.ChargesTable;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;
import us.dot.its.jpo.asn.runtime.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class ChargingFees extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "chargingSchedule", optional = true)
	@JsonProperty("chargingSchedule")
	@JacksonXmlElementWrapper(localName = "chargingSchedule")
	@JacksonXmlProperty(localName = "EventRecurrence")
	private SequenceOfChargingSchedule chargingSchedule;
	@Asn1Property(tag = 1, name = "chargesTable")
	@JsonProperty("chargesTable")
	private ChargesTable chargesTable;
	@Asn1Property(tag = 2, name = "chargingUnits")
	@JsonProperty("chargingUnits")
	private ChargingUnits chargingUnits;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfChargingSchedule extends Asn1SequenceOf<EventRecurrence> {
		public SequenceOfChargingSchedule() {
			super(EventRecurrence.class, 1L, 5L);
		}
	}

	public ChargingFees() {
		super(true);
	}
}