/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.SignalStatusMessage;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import us.dot.its.jpo.asn.j2735.r2024.Common.IntersectionReferenceID;
import us.dot.its.jpo.asn.j2735.r2024.Common.MsgCount;
import us.dot.its.jpo.asn.j2735.r2024.REGION.Reg_SignalStatus;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;
import us.dot.its.jpo.asn.runtime.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@ToString(callSuper = true)
@Getter
@Setter
public class SignalStatus extends Asn1Sequence {

  @Asn1Property(tag = 0, name = "sequenceNumber")
  @JsonProperty("sequenceNumber")
  private MsgCount sequenceNumber;

  @Asn1Property(tag = 1, name = "id")
  @JsonProperty("id")
  private IntersectionReferenceID id;

  @Asn1Property(tag = 2, name = "sigStatus")
  @JsonProperty("sigStatus")
  @JacksonXmlElementWrapper(localName = "sigStatus")
  @JacksonXmlProperty(localName = "SignalStatusPackage")
  private SignalStatusPackageList sigStatus;

  @Asn1Property(tag = 3, name = "regional", optional = true)
  @JsonProperty("regional")
  @JacksonXmlElementWrapper(localName = "regional")
  @JacksonXmlProperty(localName = "Reg-SignalStatus")
  private SequenceOfRegional regional;

  @JsonInclude(Include.NON_NULL)
  public static class SequenceOfRegional extends Asn1SequenceOf<Reg_SignalStatus> {
    public SequenceOfRegional() {
      super(Reg_SignalStatus.class, 1L, 4L);
    }
  }

  public SignalStatus() {
    super(true);
  }
}
