/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.ManeuverSharingAndCoordinatingMessage;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.Common.DDateTime;
import j2735.Common.Speed;
import j2735.Common.TemporaryID;
import lombok.Getter;
import lombok.Setter;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class SubManeuver extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "executantVehID")
	@JsonProperty("executantVehID")
	private TemporaryID executantVehID;
	@Asn1Property(tag = 1, name = "affectedVehIDs")
	@JsonProperty("affectedVehIDs")
	private TemporaryIDPointer affectedVehIDs;
	@Asn1Property(tag = 2, name = "currentStateData")
	@JsonProperty("currentStateData")
	private CurrentStateData currentStateData;
	@Asn1Property(tag = 3, name = "targetRoadResource", optional = true)
	@JsonProperty("targetRoadResource")
	private TargetRoadResource targetRoadResource;
	@Asn1Property(tag = 4, name = "startTime")
	@JsonProperty("startTime")
	private DDateTime startTime;
	@Asn1Property(tag = 5, name = "endTime")
	@JsonProperty("endTime")
	private DDateTime endTime;
	@Asn1Property(tag = 6, name = "minSpeed", optional = true)
	@JsonProperty("minSpeed")
	private Speed minSpeed;
	@Asn1Property(tag = 7, name = "maxSpeed", optional = true)
	@JsonProperty("maxSpeed")
	private Speed maxSpeed;

	public SubManeuver() {
		super(true);
	}
}