sonar.projectKey=usdot-jpo-ode_jpo-asn-pojos
sonar.organization=usdot-jpo-ode
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.java.source=25

sonar.sources=\
jpo-asn-j2735-2024/src/main/java,\
jpo-asn-runtime/src/main/java,\
jpo-asn-test-generator/src/main/java,\
jpo-asn-jsonschema-generator/src/main/java

sonar.tests=\
jpo-asn-j2735-2024/src/test/java,\
jpo-asn-runtime/src/test/java,\
jpo-asn-test-generator/src/test/java,\
jpo-asn-jsonschema-generator/src/test/java

sonar.java.binaries=\
jpo-asn-j2735-2024/build/classes/java/main,\
jpo-asn-runtime/build/classes/java/main,\
jpo-asn-test-generator/build/classes/java/main,\
jpo-asn-jsonschema-generator/build/classes/java/main

sonar.java.test.binaries=\
jpo-asn-j2735-2024/build/classes/java/test,\
jpo-asn-runtime/build/classes/java/test,\
jpo-asn-test-generator/build/classes/java/test,\
jpo-asn-jsonschema-generator/build/classes/java/test

sonar.coverage.jacoco.xmlReportPaths=\
jpo-asn-j2735-2024/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml,\
jpo-asn-test-generator/build/reports/jacoco/test/jacocoTestReport.xml,\
jpo-asn-jsonschema-generator/build/reports/jacoco/test/jacocoTestReport.xml,\
jpo-asn-runtime/build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=**/build/**,**/.gradle/**,**/gradle/**,**/generated/**
