/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.RoadUserChargingReportMessage;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.TravelerInformation.DistanceUnits;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class TripInfo extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "distanceTraveled", optional = true)
	@JsonProperty("distanceTraveled")
	private DistanceTraveledInteger distanceTraveled;
	@Asn1Property(tag = 1, name = "distanceUnits", optional = true)
	@JsonProperty("distanceUnits")
	private DistanceUnits distanceUnits;
	@Asn1Property(tag = 2, name = "timeTraveled", optional = true)
	@JsonProperty("timeTraveled")
	private TimeTraveledInteger timeTraveled;

	public static class DistanceTraveledInteger extends Asn1Integer {
		public DistanceTraveledInteger() {
			super(1L, 65535L);
		}

		@JsonCreator
		public DistanceTraveledInteger(long value) {
			this();
			this.value = value;
		}
	}

	public static class TimeTraveledInteger extends Asn1Integer {
		public TimeTraveledInteger() {
			super(1L, 600000L);
		}

		@JsonCreator
		public TimeTraveledInteger(long value) {
			this();
			this.value = value;
		}
	}

	public TripInfo() {
		super(true);
	}
}