/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.REGION;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import us.dot.its.jpo.asn.j2735.r2024.Common.RegionalExtension;
import us.dot.its.jpo.asn.runtime.annotations.Asn1ParameterizedTypes;
import us.dot.its.jpo.asn.runtime.annotations.Asn1ParameterizedTypes.IdType;
import us.dot.its.jpo.asn.runtime.serialization.ParameterizedTypeDeserializer;

@JsonInclude(Include.NON_NULL)
@Asn1ParameterizedTypes(
    idProperty = "regionId",
    idType = IdType.INTEGER,
    valueProperty = "regExtValue",
    value = {
      @Asn1ParameterizedTypes.Type(
          value =
              us.dot.its.jpo.asn.j2735.r2024.AddGrpC.IntersectionState_addGrpCReg_IntersectionState
                  .class,
          intId = 3)
    })
@JsonDeserialize(
    using =
        us.dot.its.jpo.asn.j2735.r2024.REGION.Reg_IntersectionState
            .Reg_IntersectionStateDeserializer.class)
public abstract class Reg_IntersectionState<TValue> extends RegionalExtension<TValue> {

  public Reg_IntersectionState(int id, String name) {
    super(id, name);
  }

  @java.lang.SuppressWarnings("rawtypes")
  public static class Reg_IntersectionStateDeserializer
      extends ParameterizedTypeDeserializer<Reg_IntersectionState> {
    public Reg_IntersectionStateDeserializer() {
      super(Reg_IntersectionState.class);
    }
  }
}
