/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.ProbeDataManagement;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedSerializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Enumerated;

@Getter
@JsonSerialize(using = VehicleStatusDeviceTypeTag.VehicleStatusDeviceTypeTagSerializer.class)
@JsonDeserialize(using = VehicleStatusDeviceTypeTag.VehicleStatusDeviceTypeTagDeserializer.class)
public enum VehicleStatusDeviceTypeTag implements Asn1Enumerated {
  UNKNOWN(0, "unknown"),
  LIGHTS(1, "lights"),
  WIPERS(2, "wipers"),
  BRAKES(3, "brakes"),
  STAB(4, "stab"),
  TRAC(5, "trac"),
  ABS(6, "abs"),
  SUNS(7, "sunS"),
  RAINS(8, "rainS"),
  AIRTEMP(9, "airTemp"),
  STEERING(10, "steering"),
  VERTACCELTHRES(11, "vertAccelThres"),
  VERTACCEL(12, "vertAccel"),
  HOZACCELLONG(13, "hozAccelLong"),
  HOZACCELLAT(14, "hozAccelLat"),
  HOZACCELCON(15, "hozAccelCon"),
  ACCEL4WAY(16, "accel4way"),
  CONFIDENCESET(17, "confidenceSet"),
  OBDIST(18, "obDist"),
  OBDIRECT(19, "obDirect"),
  YAW(20, "yaw"),
  YAWRATECON(21, "yawRateCon"),
  DATETIME(22, "dateTime"),
  FULLPOS(23, "fullPos"),
  POSITION2D(24, "position2D"),
  POSITION3D(25, "position3D"),
  VEHICLE(26, "vehicle"),
  SPEEDHEADC(27, "speedHeadC"),
  SPEEDC(28, "speedC");

  private final int index;
  private final String name;

  private VehicleStatusDeviceTypeTag(int index, String name) {
    this.index = index;
    this.name = name;
  }

  public static class VehicleStatusDeviceTypeTagSerializer
      extends EnumeratedSerializer<VehicleStatusDeviceTypeTag> {
    public VehicleStatusDeviceTypeTagSerializer() {
      super(VehicleStatusDeviceTypeTag.class);
    }
  }

  public static class VehicleStatusDeviceTypeTagDeserializer
      extends EnumeratedDeserializer<VehicleStatusDeviceTypeTag> {
    public VehicleStatusDeviceTypeTagDeserializer() {
      super(VehicleStatusDeviceTypeTag.class);
    }

    @Override
    protected VehicleStatusDeviceTypeTag[] listEnumValues() {
      return VehicleStatusDeviceTypeTag.values();
    }
  }
}
