/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.BasicSafetyMessage;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.asn.j2735.r2024.Common.Axles;
import us.dot.its.jpo.asn.j2735.r2024.Common.BumperHeights;
import us.dot.its.jpo.asn.j2735.r2024.Common.TrailerWeight;
import us.dot.its.jpo.asn.j2735.r2024.Common.VehicleHeight;
import us.dot.its.jpo.asn.j2735.r2024.Common.VehicleMass;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Boolean;
import us.dot.its.jpo.asn.runtime.types.Asn1Integer;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class VehicleData extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "height", optional = true)
	@JsonProperty("height")
	private VehicleHeight height;
	@Asn1Property(tag = 1, name = "bumpers", optional = true)
	@JsonProperty("bumpers")
	private BumperHeights bumpers;
	@Asn1Property(tag = 2, name = "mass", optional = true)
	@JsonProperty("mass")
	private VehicleMass mass;
	@Asn1Property(tag = 3, name = "doNotUse", optional = true)
	@JsonProperty("doNotUse")
	private TrailerWeight doNotUse;
	@Asn1Property(tag = 4, name = "trailerPresent", optional = true, extension = true)
	@JsonProperty("trailerPresent")
	private Asn1Boolean trailerPresent;
	@Asn1Property(tag = 5, name = "pivotPoint", optional = true, extension = true)
	@JsonProperty("pivotPoint")
	private PivotPointDescription pivotPoint;
	@Asn1Property(tag = 6, name = "axles", optional = true, extension = true)
	@JsonProperty("axles")
	private Axles axles;
	@Asn1Property(tag = 7, name = "leanAngle", optional = true, extension = true)
	@JsonProperty("leanAngle")
	private LeanAngleInteger leanAngle;

	public static class LeanAngleInteger extends Asn1Integer {
		public LeanAngleInteger() {
			super(-90L, 90L);
		}

		@JsonCreator
		public LeanAngleInteger(long value) {
			this();
			this.value = value;
		}
	}

	public VehicleData() {
		super(true);
	}
}