/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.BasicSafetyMessage;

import asn2pojo.runtime.annotations.Asn1ParameterizedTypes;
import asn2pojo.runtime.annotations.Asn1ParameterizedTypes.IdType;
import asn2pojo.runtime.serialization.ParameterizedTypeDeserializer;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonInclude(Include.NON_NULL)
@Asn1ParameterizedTypes(idProperty = "partII-Id", idType = IdType.INTEGER, valueProperty = "partII-Value", value = {
		@Asn1ParameterizedTypes.Type(value = j2735.Common.VehicleSafetyExtensionsBSMpartIIExtension.class, intId = 0),
		@Asn1ParameterizedTypes.Type(value = SpecialVehicleExtensionsBSMpartIIExtension.class, intId = 1),
		@Asn1ParameterizedTypes.Type(value = SupplementalVehicleExtensionsBSMpartIIExtension.class, intId = 2)})
@JsonDeserialize(using = BSMpartIIExtension.BSMpartIIExtensionDeserializer.class)
abstract public class BSMpartIIExtension<TValue> extends PartIIcontent<TValue> {

	public BSMpartIIExtension(int id, String name) {
		super(id, name);
	}

	public static class BSMpartIIExtensionDeserializer extends ParameterizedTypeDeserializer<BSMpartIIExtension> {
		public BSMpartIIExtensionDeserializer() {
			super(BSMpartIIExtension.class);
		}
	}
}