/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.TollAdvertisementMessage;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.serialization.EnumeratedDeserializer;
import asn2pojo.runtime.serialization.EnumeratedSerializer;
import asn2pojo.runtime.types.Asn1Enumerated;
import asn2pojo.runtime.types.Asn1Integer;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import j2735.EfcDataDictionary.PaymentFee;
import lombok.Getter;
import lombok.Setter;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class PerAxleWeightCharges extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "totalWeightLimit")
	@JsonProperty("totalWeightLimit")
	private TotalWeightLimitInteger totalWeightLimit;
	@Asn1Property(tag = 1, name = "maxLadenWeightOnAxle")
	@JsonProperty("maxLadenWeightOnAxle")
	private MaxLadenWeightOnAxleInteger maxLadenWeightOnAxle;
	@Asn1Property(tag = 2, name = "weightLimitUnits")
	@JsonProperty("weightLimitUnits")
	private EnumeratedWeightLimitUnits weightLimitUnits;
	@Asn1Property(tag = 3, name = "axleWeightCharge")
	@JsonProperty("axleWeightCharge")
	private PaymentFee axleWeightCharge;

	public static class TotalWeightLimitInteger extends Asn1Integer {
		public TotalWeightLimitInteger() {
			super(0L, 16777215L);
		}

		@JsonCreator
		public TotalWeightLimitInteger(long value) {
			this();
			this.value = value;
		}
	}

	public static class MaxLadenWeightOnAxleInteger extends Asn1Integer {
		public MaxLadenWeightOnAxleInteger() {
			super(0L, 65535L);
		}

		@JsonCreator
		public MaxLadenWeightOnAxleInteger(long value) {
			this();
			this.value = value;
		}
	}

	@Getter
	@JsonSerialize(using = EnumeratedWeightLimitUnitsSerializer.class)
	@JsonDeserialize(using = EnumeratedWeightLimitUnitsDeserializer.class)
	public static enum EnumeratedWeightLimitUnits implements Asn1Enumerated {
		POUNDS(0, "pounds"), KILOGRAMS(1, "kilograms");

		private final int index;
		private final String name;

		private EnumeratedWeightLimitUnits(int index, String name) {
			this.index = index;
			this.name = name;
		}
	}

	public static class EnumeratedWeightLimitUnitsSerializer extends EnumeratedSerializer<EnumeratedWeightLimitUnits> {
		EnumeratedWeightLimitUnitsSerializer() {
			super(EnumeratedWeightLimitUnits.class);
		}
	}

	public static class EnumeratedWeightLimitUnitsDeserializer
			extends
				EnumeratedDeserializer<EnumeratedWeightLimitUnits> {
		EnumeratedWeightLimitUnitsDeserializer() {
			super(EnumeratedWeightLimitUnits.class);
		}

		@Override
		protected EnumeratedWeightLimitUnits[] listEnumValues() {
			return EnumeratedWeightLimitUnits.values();
		}
	}

	public PerAxleWeightCharges() {
		super(true);
	}
}