/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.TollAdvertisementMessage;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.serialization.SequenceOfChoiceDeserializer;
import asn2pojo.runtime.serialization.SequenceOfChoiceSerializer;
import asn2pojo.runtime.types.Asn1Choice;
import asn2pojo.runtime.types.Asn1Sequence;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.Getter;
import lombok.Setter;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class TollChargesTable extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "tollTypeCharge")
	@JsonProperty("tollTypeCharge")
	private TollTypeChargeChoice tollTypeCharge;

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class TollTypeChargeChoice extends Asn1Choice {
		@Asn1Property(tag = 0, name = "pointCharges")
		@JsonProperty("pointCharges")
		private ChargesTable pointCharges;
		@Asn1Property(tag = 1, name = "perLaneCharges")
		@JsonProperty("perLaneCharges")
		@JacksonXmlElementWrapper(localName = "perLaneCharges")
		@JacksonXmlProperty(localName = "LaneChargesTable")
		private SequenceOfPerLaneCharges perLaneCharges;
		@Asn1Property(tag = 2, name = "closedNetworkCharges")
		@JsonProperty("closedNetworkCharges")
		@JsonSerialize(using = SequenceOfClosedNetworkChargesSerializer.class)
		@JsonDeserialize(using = SequenceOfClosedNetworkChargesDeserializer.class)
		private SequenceOfClosedNetworkCharges closedNetworkCharges;
		@Asn1Property(tag = 3, name = "timeBasedCharges")
		@JsonProperty("timeBasedCharges")
		private TimeChargesTable timeBasedCharges;

		public TollTypeChargeChoice() {
			super(true);
		}

		@JsonInclude(Include.NON_NULL)
		public static class SequenceOfPerLaneCharges extends Asn1SequenceOf<LaneChargesTable> {
			public SequenceOfPerLaneCharges() {
				super(LaneChargesTable.class, 1L, 64L);
			}
		}

		@JsonInclude(Include.NON_NULL)
		public static class SequenceOfClosedNetworkCharges extends Asn1SequenceOf<ClosedNetworkChargesTable> {
			public SequenceOfClosedNetworkCharges() {
				super(ClosedNetworkChargesTable.class, 1L, 64L);
			}
		}

		public static class SequenceOfClosedNetworkChargesSerializer
				extends
					SequenceOfChoiceSerializer<ClosedNetworkChargesTable, SequenceOfClosedNetworkCharges> {
			public SequenceOfClosedNetworkChargesSerializer() {
				super(ClosedNetworkChargesTable.class, SequenceOfClosedNetworkCharges.class);
			}
		}

		public static class SequenceOfClosedNetworkChargesDeserializer
				extends
					SequenceOfChoiceDeserializer<ClosedNetworkChargesTable, SequenceOfClosedNetworkCharges> {
			public SequenceOfClosedNetworkChargesDeserializer() {
				super(ClosedNetworkChargesTable.class, SequenceOfClosedNetworkCharges.class);
			}

			@Override
			protected SequenceOfClosedNetworkCharges construct() {
				return new SequenceOfClosedNetworkCharges();
			}
		}
	}

	public TollChargesTable() {
		super(true);
	}
}