/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.TollAdvertisementMessage;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;

@Getter
@JsonSerialize(using = VehicleTypesSerializer.class)
@JsonDeserialize(using = VehicleTypesDeserializer.class)
public enum VehicleTypes implements Asn1Enumerated {
	MOTORCYCLES(1, "motorcycles"), PASSENGERCARS(2, "passengerCars"), FOURTIRESINGLEUNIT(3,
			"fourTireSingleUnit"), BUSES(4, "buses"), TWOAXLESIXTIRESINGLEUNIT(5,
					"twoAxleSixTireSingleUnit"), THREEAXLESINGLEUNIT(6,
							"threeAxleSingleUnit"), FOURORMOREAXLESINGLEUNIT(7,
									"fourOrMoreAxleSingleUnit"), FOURORLESSAXLESINGLETRAILER(8,
											"fourOrLessAxleSingleTrailer"), FIVEAXLETRACTORSEMITRAILER(9,
													"fiveAxleTractorSemitrailer"), SIXORMOREAXLESINGLETRAILER(10,
															"sixOrMoreAxleSingleTrailer"), FIVEORLESSAXLEMULTITRAILER(
																	11,
																	"fiveOrLessAxleMultiTrailer"), SIXAXLEMULTITRAILER(
																			12,
																			"sixAxleMultiTrailer"), SEVENORMOREAXLEMULTITRAILER(
																					13, "sevenOrMoreAxleMultiTrailer");

	private final int index;
	private final String name;

	private VehicleTypes(int index, String name) {
		this.index = index;
		this.name = name;
	}
}