/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.AddGrpB;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedSerializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Enumerated;

@Getter
@JsonSerialize(using = DayOfWeek.DayOfWeekSerializer.class)
@JsonDeserialize(using = DayOfWeek.DayOfWeekDeserializer.class)
public enum DayOfWeek implements Asn1Enumerated {
  UNKNOWN(0, "unknown"),
  MONDAY(1, "monday"),
  TUESDAY(2, "tuesday"),
  WEDNESDAY(3, "wednesday"),
  THURSDAY(4, "thursday"),
  FRIDAY(5, "friday"),
  SATURDAY(6, "saturday"),
  SUNDAY(7, "sunday");

  private final int index;
  private final String name;

  private DayOfWeek(int index, String name) {
    this.index = index;
    this.name = name;
  }

  public static class DayOfWeekSerializer extends EnumeratedSerializer<DayOfWeek> {
    public DayOfWeekSerializer() {
      super(DayOfWeek.class);
    }
  }

  public static class DayOfWeekDeserializer extends EnumeratedDeserializer<DayOfWeek> {
    public DayOfWeekDeserializer() {
      super(DayOfWeek.class);
    }

    @Override
    protected DayOfWeek[] listEnumValues() {
      return DayOfWeek.values();
    }
  }
}
