/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.SPAT;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.REGION.Reg_MovementEvent;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class MovementEvent extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "eventState")
	@JsonProperty("eventState")
	private MovementPhaseState eventState;
	@Asn1Property(tag = 1, name = "timing", optional = true)
	@JsonProperty("timing")
	private TimeChangeDetails timing;
	@Asn1Property(tag = 2, name = "speeds", optional = true)
	@JsonProperty("speeds")
	@JacksonXmlElementWrapper(localName = "speeds")
	@JacksonXmlProperty(localName = "AdvisorySpeed")
	private AdvisorySpeedList speeds;
	@Asn1Property(tag = 3, name = "regional", optional = true)
	@JsonProperty("regional")
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_MovementEvent> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_MovementEvent.class, 1L, 4L);
		}
	}

	MovementEvent() {
		super(true);
	}
}