/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.MapData;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.asn.j2735.r2024.Common.ApproachID;
import us.dot.its.jpo.asn.j2735.r2024.Common.DescriptiveName;
import us.dot.its.jpo.asn.j2735.r2024.Common.LaneID;
import us.dot.its.jpo.asn.j2735.r2024.Common.NodeListXY;
import us.dot.its.jpo.asn.j2735.r2024.REGION.Reg_GenericLane;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;
import us.dot.its.jpo.asn.runtime.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class GenericLane extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "laneID")
	@JsonProperty("laneID")
	private LaneID laneID;
	@Asn1Property(tag = 1, name = "name", optional = true)
	@JsonProperty("name")
	private DescriptiveName name;
	@Asn1Property(tag = 2, name = "ingressApproach", optional = true)
	@JsonProperty("ingressApproach")
	private ApproachID ingressApproach;
	@Asn1Property(tag = 3, name = "egressApproach", optional = true)
	@JsonProperty("egressApproach")
	private ApproachID egressApproach;
	@Asn1Property(tag = 4, name = "laneAttributes")
	@JsonProperty("laneAttributes")
	private LaneAttributes laneAttributes;
	@Asn1Property(tag = 5, name = "maneuvers", optional = true)
	@JsonProperty("maneuvers")
	private AllowedManeuvers maneuvers;
	@Asn1Property(tag = 6, name = "nodeList")
	@JsonProperty("nodeList")
	private NodeListXY nodeList;
	@Asn1Property(tag = 7, name = "connectsTo", optional = true)
	@JsonProperty("connectsTo")
	@JacksonXmlElementWrapper(localName = "connectsTo")
	@JacksonXmlProperty(localName = "Connection")
	private ConnectsToList connectsTo;
	@Asn1Property(tag = 8, name = "overlays", optional = true)
	@JsonProperty("overlays")
	@JacksonXmlElementWrapper(localName = "overlays")
	@JacksonXmlProperty(localName = "LaneID")
	private OverlayLaneList overlays;
	@Asn1Property(tag = 9, name = "regional", optional = true)
	@JsonProperty("regional")
	@JacksonXmlElementWrapper(localName = "regional")
	@JacksonXmlProperty(localName = "Reg-GenericLane")
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_GenericLane> {
		public SequenceOfRegional() {
			super(Reg_GenericLane.class, 1L, 4L);
		}
	}

	public GenericLane() {
		super(true);
	}
}