/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.MapData;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import us.dot.its.jpo.asn.runtime.serialization.BitStringDeserializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Bitstring;

@JsonDeserialize(
    using =
        us.dot.its.jpo.asn.j2735.r2024.MapData.LaneAttributes_TrackedVehicle
            .LaneAttributes_TrackedVehicleDeserializer.class)
public class LaneAttributes_TrackedVehicle extends Asn1Bitstring {

  public boolean isSpec_RevocableLane() {
    return get(0);
  }

  public void setSpec_RevocableLane(boolean spec_RevocableLane) {
    set(0, spec_RevocableLane);
  }

  public boolean isSpec_commuterRailRoadTrack() {
    return get(1);
  }

  public void setSpec_commuterRailRoadTrack(boolean spec_commuterRailRoadTrack) {
    set(1, spec_commuterRailRoadTrack);
  }

  public boolean isSpec_lightRailRoadTrack() {
    return get(2);
  }

  public void setSpec_lightRailRoadTrack(boolean spec_lightRailRoadTrack) {
    set(2, spec_lightRailRoadTrack);
  }

  public boolean isSpec_heavyRailRoadTrack() {
    return get(3);
  }

  public void setSpec_heavyRailRoadTrack(boolean spec_heavyRailRoadTrack) {
    set(3, spec_heavyRailRoadTrack);
  }

  public boolean isSpec_otherRailType() {
    return get(4);
  }

  public void setSpec_otherRailType(boolean spec_otherRailType) {
    set(4, spec_otherRailType);
  }

  public LaneAttributes_TrackedVehicle() {
    super(
        16,
        false,
        new String[] {
          "spec-RevocableLane",
          "spec-commuterRailRoadTrack",
          "spec-lightRailRoadTrack",
          "spec-heavyRailRoadTrack",
          "spec-otherRailType"
        });
  }

  public static class LaneAttributes_TrackedVehicleDeserializer
      extends BitStringDeserializer<LaneAttributes_TrackedVehicle> {
    public LaneAttributes_TrackedVehicleDeserializer() {
      super(LaneAttributes_TrackedVehicle.class);
    }

    @Override
    protected LaneAttributes_TrackedVehicle construct() {
      return new LaneAttributes_TrackedVehicle();
    }
  }
}
