/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.Common;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedSerializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Enumerated;

@Getter
@JsonSerialize(using = PortlandCementType.PortlandCementTypeSerializer.class)
@JsonDeserialize(using = PortlandCementType.PortlandCementTypeDeserializer.class)
public enum PortlandCementType implements Asn1Enumerated {
	NEWSHARP(0, "newSharp"), TRAVELED(1, "traveled"), TRAFFICPOLISHED(2, "trafficPolished");

	private final int index;
	private final String name;

	private PortlandCementType(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public static class PortlandCementTypeSerializer extends EnumeratedSerializer<PortlandCementType> {
		public PortlandCementTypeSerializer() {
			super(PortlandCementType.class);
		}
	}

	public static class PortlandCementTypeDeserializer extends EnumeratedDeserializer<PortlandCementType> {
		public PortlandCementTypeDeserializer() {
			super(PortlandCementType.class);
		}

		@Override
		protected PortlandCementType[] listEnumValues() {
			return PortlandCementType.values();
		}
	}
}