/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.Common;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedSerializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Enumerated;

@Getter
@JsonSerialize(using = HeadingConfidence.HeadingConfidenceSerializer.class)
@JsonDeserialize(using = HeadingConfidence.HeadingConfidenceDeserializer.class)
public enum HeadingConfidence implements Asn1Enumerated {
  UNAVAILABLE(0, "unavailable"),
  PREC10DEG(1, "prec10deg"),
  PREC05DEG(2, "prec05deg"),
  PREC01DEG(3, "prec01deg"),
  PREC0_1DEG(4, "prec0-1deg"),
  PREC0_05DEG(5, "prec0-05deg"),
  PREC0_01DEG(6, "prec0-01deg"),
  PREC0_0125DEG(7, "prec0-0125deg");

  private final int index;
  private final String name;

  private HeadingConfidence(int index, String name) {
    this.index = index;
    this.name = name;
  }

  public static class HeadingConfidenceSerializer extends EnumeratedSerializer<HeadingConfidence> {
    public HeadingConfidenceSerializer() {
      super(HeadingConfidence.class);
    }
  }

  public static class HeadingConfidenceDeserializer
      extends EnumeratedDeserializer<HeadingConfidence> {
    public HeadingConfidenceDeserializer() {
      super(HeadingConfidence.class);
    }

    @Override
    protected HeadingConfidence[] listEnumValues() {
      return HeadingConfidence.values();
    }
  }
}
