/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.Common;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedSerializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Enumerated;

@Getter
@JsonSerialize(using = Location_quality.Location_qualitySerializer.class)
@JsonDeserialize(using = Location_quality.Location_qualityDeserializer.class)
public enum Location_quality implements Asn1Enumerated {
  LOC_QUAL_BT1M(0, "loc-qual-bt1m"),
  LOC_QUAL_BT5M(1, "loc-qual-bt5m"),
  LOC_QUAL_BT12M(2, "loc-qual-bt12m"),
  LOC_QUAL_BT50M(3, "loc-qual-bt50m"),
  LOC_QUAL_BT125M(4, "loc-qual-bt125m"),
  LOC_QUAL_BT500M(5, "loc-qual-bt500m"),
  LOC_QUAL_BT1250M(6, "loc-qual-bt1250m"),
  LOC_QUAL_UNKNOWN(7, "loc-qual-unknown");

  private final int index;
  private final String name;

  private Location_quality(int index, String name) {
    this.index = index;
    this.name = name;
  }

  public static class Location_qualitySerializer extends EnumeratedSerializer<Location_quality> {
    public Location_qualitySerializer() {
      super(Location_quality.class);
    }
  }

  public static class Location_qualityDeserializer
      extends EnumeratedDeserializer<Location_quality> {
    public Location_qualityDeserializer() {
      super(Location_quality.class);
    }

    @Override
    protected Location_quality[] listEnumValues() {
      return Location_quality.values();
    }
  }
}
