/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.Common;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;

@JsonPropertyOrder({"regionId", "regExtValue"})
public abstract class RegionalExtension<TValue> extends Asn1Sequence {

  protected RegionId regionId;
  @JsonIgnore protected final String name;
  protected TValue regExtValue;

  @JsonProperty("regionId")
  public RegionId getRegionId() {
    return regionId;
  }

  @JsonProperty("regionId")
  public void setRegionId(RegionId regionId) {
    this.regionId = regionId;
  }

  public String getName() {
    return name;
  }

  @JsonProperty("regExtValue")
  public TValue getRegExtValue() {
    return regExtValue;
  }

  @JsonProperty("regExtValue")
  public void setRegExtValue(TValue regExtValue) {
    this.regExtValue = regExtValue;
  }

  public RegionalExtension(int id, String name) {
    var theId = new us.dot.its.jpo.asn.j2735.r2024.Common.RegionId();
    theId.setValue(id);
    this.regionId = theId;
    this.name = name;
  }

  @Override
  public boolean hasExtensionMarker() {
    return true;
  }
}
