/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.Common;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.JsonDeserializer.None;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import us.dot.its.jpo.asn.j2735.r2024.CooperativeControlMessage.CCMpartIIExtension;
import us.dot.its.jpo.asn.runtime.serialization.OpenTypeDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.OpenTypeSerializer;

@JsonRootName("CCMpartIIExtension")
@JsonDeserialize(using = None.class)
public class VehicleSafetyExtensionsCCMpartIIExtension
    extends CCMpartIIExtension<VehicleSafetyExtensions> {

  public VehicleSafetyExtensionsCCMpartIIExtension() {
    super(0, "VehicleSafetyExtensions");
  }

  @Override
  @JsonSerialize(using = VehicleSafetyExtensionsCCMpartIIExtensionValueSerializer.class)
  public VehicleSafetyExtensions getPartII_Value() {
    return super.getPartII_Value();
  }

  @Override
  @JsonDeserialize(using = VehicleSafetyExtensionsCCMpartIIExtensionValueDeserializer.class)
  public void setPartII_Value(VehicleSafetyExtensions value) {
    super.setPartII_Value(value);
  }

  public static class VehicleSafetyExtensionsCCMpartIIExtensionValueSerializer
      extends OpenTypeSerializer<VehicleSafetyExtensions> {
    public VehicleSafetyExtensionsCCMpartIIExtensionValueSerializer() {
      super(VehicleSafetyExtensions.class, "partII-Value", "VehicleSafetyExtensions");
    }
  }

  public static class VehicleSafetyExtensionsCCMpartIIExtensionValueDeserializer
      extends OpenTypeDeserializer<VehicleSafetyExtensions> {
    public VehicleSafetyExtensionsCCMpartIIExtensionValueDeserializer() {
      super(VehicleSafetyExtensions.class, "VehicleSafetyExtensions");
    }
  }
}
