/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.REGION;

import asn2pojo.runtime.annotations.Asn1ParameterizedTypes;
import asn2pojo.runtime.annotations.Asn1ParameterizedTypes.IdType;
import asn2pojo.runtime.serialization.ParameterizedTypeDeserializer;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import j2735.Common.RegionalExtension;

@JsonInclude(Include.NON_NULL)
@Asn1ParameterizedTypes(idProperty = "regionId", idType = IdType.INTEGER, valueProperty = "regExtValue", value = {
		@Asn1ParameterizedTypes.Type(value = j2735.AddGrpB.LaneDataAttribute_addGrpBReg_LaneDataAttribute.class, intId = 2)})
@JsonDeserialize(using = Reg_LaneDataAttribute.Reg_LaneDataAttributeDeserializer.class)
abstract public class Reg_LaneDataAttribute<TValue> extends RegionalExtension<TValue> {

	public Reg_LaneDataAttribute(int id, String name) {
		super(id, name);
	}

	public static class Reg_LaneDataAttributeDeserializer extends ParameterizedTypeDeserializer<Reg_LaneDataAttribute> {
		public Reg_LaneDataAttributeDeserializer() {
			super(Reg_LaneDataAttribute.class);
		}
	}
}