/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.MapData;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;

@Getter
@JsonSerialize(using = LayerTypeSerializer.class)
@JsonDeserialize(using = LayerTypeDeserializer.class)
public enum LayerType implements Asn1Enumerated {
	NONE(0, "none"), MIXEDCONTENT(1, "mixedContent"), GENERALMAPDATA(2, "generalMapData"), INTERSECTIONDATA(3,
			"intersectionData"), CURVEDATA(4, "curveData"), ROADWAYSECTIONDATA(5,
					"roadwaySectionData"), PARKINGAREADATA(6, "parkingAreaData"), SHAREDLANEDATA(7, "sharedLaneData");

	private final int index;
	private final String name;

	private LayerType(int index, String name) {
		this.index = index;
		this.name = name;
	}
}