/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.MapData;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import j2735.Common.DescriptiveName;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.Common.RoadSegmentReferenceID;
import j2735.Common.MsgCount;
import j2735.Common.Position3D;
import j2735.Common.LaneWidth;
import j2735.Common.SpeedLimitList;
import j2735.REGION.Reg_RoadSegment;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class RoadSegment extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "name", optional = true)
	@JsonProperty("name")
	private DescriptiveName name;
	@Asn1Property(tag = 1, name = "id")
	@JsonProperty("id")
	private RoadSegmentReferenceID id;
	@Asn1Property(tag = 2, name = "revision")
	@JsonProperty("revision")
	private MsgCount revision;
	@Asn1Property(tag = 3, name = "refPoint")
	@JsonProperty("refPoint")
	private Position3D refPoint;
	@Asn1Property(tag = 4, name = "laneWidth", optional = true)
	@JsonProperty("laneWidth")
	private LaneWidth laneWidth;
	@Asn1Property(tag = 5, name = "speedLimits", optional = true)
	@JsonProperty("speedLimits")
	@JacksonXmlElementWrapper(localName = "speedLimits")
	@JacksonXmlProperty(localName = "RegulatorySpeedLimit")
	private SpeedLimitList speedLimits;
	@Asn1Property(tag = 6, name = "roadLaneSet")
	@JsonProperty("roadLaneSet")
	@JacksonXmlElementWrapper(localName = "roadLaneSet")
	@JacksonXmlProperty(localName = "GenericLane")
	private RoadLaneSetList roadLaneSet;
	@Asn1Property(tag = 7, name = "regional", optional = true)
	@JsonProperty("regional")
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_RoadSegment> {
		public SequenceOfRegional() {
			super(j2735.REGION.Reg_RoadSegment.class, 1L, 4L);
		}
	}

	public RoadSegment() {
		super(true);
	}
}