/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.TollUsageAckMessage;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class TollUsageAckMessage extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "tumAck")
	@JsonProperty("tumAck")
	@JacksonXmlElementWrapper(localName = "tumAck")
	@JacksonXmlProperty(localName = "TumAckHash")
	private TumAck tumAck;
	@Asn1Property(tag = 1, name = "ackMaxAge")
	@JsonProperty("ackMaxAge")
	private AckMaxAgeInteger ackMaxAge;

	public static class AckMaxAgeInteger extends Asn1Integer {
		public AckMaxAgeInteger() {
			super(100L, 10000L);
		}

		@JsonCreator
		public AckMaxAgeInteger(long value) {
			this();
			this.value = value;
		}
	}

	TollUsageAckMessage() {
		super(true);
	}
}