/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.RoadSafetyMessage;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.serialization.EnumeratedDeserializer;
import asn2pojo.runtime.serialization.EnumeratedSerializer;
import asn2pojo.runtime.types.Asn1Enumerated;
import asn2pojo.runtime.types.Asn1Sequence;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.Getter;
import lombok.Setter;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class DynamicInfoContainer extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "priority")
	@JsonProperty("priority")
	private EnumeratedPriority priority;
	@Asn1Property(tag = 1, name = "dmsSignString")
	@JsonProperty("dmsSignString")
	@JacksonXmlElementWrapper(localName = "dmsSignString")
	@JacksonXmlProperty(localName = "ShortString")
	private SequenceOfDmsSignString dmsSignString;
	@Asn1Property(tag = 2, name = "applicableRegion")
	@JsonProperty("applicableRegion")
	private RegionInfo applicableRegion;

	@Getter
	@JsonSerialize(using = EnumeratedPrioritySerializer.class)
	@JsonDeserialize(using = EnumeratedPriorityDeserializer.class)
	public enum EnumeratedPriority implements Asn1Enumerated {
		LOW_PRIORITY(0, "low-priority"), MEDIUM_PRIORITY(1, "medium-priority"), HIGH_PRIORITY(2,
				"high-priority"), CRITICAL(3, "critical");

		private final int index;
		private final String name;

		private EnumeratedPriority(int index, String name) {
			this.index = index;
			this.name = name;
		}
	}

	public static class EnumeratedPrioritySerializer extends EnumeratedSerializer<EnumeratedPriority> {
		public EnumeratedPrioritySerializer() {
			super(EnumeratedPriority.class);
		}
	}

	public static class EnumeratedPriorityDeserializer extends EnumeratedDeserializer<EnumeratedPriority> {
		public EnumeratedPriorityDeserializer() {
			super(EnumeratedPriority.class);
		}

		@Override
		protected EnumeratedPriority[] listEnumValues() {
			return EnumeratedPriority.values();
		}
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfDmsSignString extends Asn1SequenceOf<ShortString> {
		public SequenceOfDmsSignString() {
			super(ShortString.class, 0L, 2147483647L);
		}
	}

	public DynamicInfoContainer() {
		super(true);
	}
}