/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.RoadSafetyMessage;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.types.Asn1SequenceOf;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class LaneClosureContainer extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "laneStatus", optional = true)
	@JsonProperty("laneStatus")
	private SequenceOfLaneStatus laneStatus;
	@Asn1Property(tag = 1, name = "laneStatusVaries", optional = true)
	@JsonProperty("laneStatusVaries")
	private Activity laneStatusVaries;
	@Asn1Property(tag = 2, name = "closureRegion")
	@JsonProperty("closureRegion")
	private RegionInfo closureRegion;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfLaneStatus extends Asn1SequenceOf<LaneInfo> {
		SequenceOfLaneStatus() {
			super(LaneInfo.class, 1L, 10L);
		}
	}

	LaneClosureContainer() {
		super(true);
	}
}