/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.MessageFrame;

import asn2pojo.runtime.annotations.Asn1ParameterizedTypes;
import asn2pojo.runtime.annotations.Asn1ParameterizedTypes.IdType;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;

@JsonTypeInfo(use = Id.NAME, include = As.EXISTING_PROPERTY, property = "messageId")
@JsonSubTypes({@JsonSubTypes.Type(value = j2735.BasicSafetyMessage.BasicSafetyMessageMessageFrame.class, name = "20"),
		@JsonSubTypes.Type(value = j2735.MapData.MapDataMessageFrame.class, name = "18"),
		@JsonSubTypes.Type(value = j2735.SPAT.SPATMessageFrame.class, name = "19"),
		@JsonSubTypes.Type(value = j2735.CommonSafetyRequest.CommonSafetyRequestMessageFrame.class, name = "21"),
		@JsonSubTypes.Type(value = j2735.EmergencyVehicleAlert.EmergencyVehicleAlertMessageFrame.class, name = "22"),
		@JsonSubTypes.Type(value = j2735.IntersectionCollision.IntersectionCollisionMessageFrame.class, name = "23"),
		@JsonSubTypes.Type(value = j2735.NMEAcorrections.NMEAcorrectionsMessageFrame.class, name = "24"),
		@JsonSubTypes.Type(value = j2735.ProbeDataManagement.ProbeDataManagementMessageFrame.class, name = "25"),
		@JsonSubTypes.Type(value = j2735.ProbeVehicleData.ProbeVehicleDataMessageFrame.class, name = "26"),
		@JsonSubTypes.Type(value = j2735.RoadSideAlert.RoadSideAlertMessageFrame.class, name = "27"),
		@JsonSubTypes.Type(value = j2735.RTCMcorrections.RTCMcorrectionsMessageFrame.class, name = "28"),
		@JsonSubTypes.Type(value = j2735.SignalRequestMessage.SignalRequestMessageMessageFrame.class, name = "29"),
		@JsonSubTypes.Type(value = j2735.SignalStatusMessage.SignalStatusMessageMessageFrame.class, name = "30"),
		@JsonSubTypes.Type(value = j2735.TravelerInformation.TravelerInformationMessageFrame.class, name = "31"),
		@JsonSubTypes.Type(value = j2735.PersonalSafetyMessage.PersonalSafetyMessageMessageFrame.class, name = "32"),
		@JsonSubTypes.Type(value = j2735.RoadSafetyMessage.RoadSafetyMessageMessageFrame.class, name = "33"),
		@JsonSubTypes.Type(value = j2735.RoadWeatherMessage.RoadWeatherMessageMessageFrame.class, name = "34"),
		@JsonSubTypes.Type(value = j2735.ProbeDataConfig.ProbeDataConfigMessageMessageFrame.class, name = "35"),
		@JsonSubTypes.Type(value = j2735.ProbeDataReport.ProbeDataReportMessageMessageFrame.class, name = "36"),
		@JsonSubTypes.Type(value = j2735.TollAdvertisementMessage.TollAdvertisementMessageMessageFrame.class, name = "37"),
		@JsonSubTypes.Type(value = j2735.TollUsageMessage.TollUsageMessageMessageFrame.class, name = "38"),
		@JsonSubTypes.Type(value = j2735.TollUsageAckMessage.TollUsageAckMessageMessageFrame.class, name = "39"),
		@JsonSubTypes.Type(value = j2735.CooperativeControlMessage.CooperativeControlMessageMessageFrame.class, name = "40"),
		@JsonSubTypes.Type(value = j2735.SensorDataSharingMessage.SensorDataSharingMessageMessageFrame.class, name = "41"),
		@JsonSubTypes.Type(value = j2735.ManeuverSharingAndCoordinatingMessage.ManeuverSharingAndCoordinatingMessageMessageFrame.class, name = "42"),
		@JsonSubTypes.Type(value = j2735.RoadGeometryAndAttributes.RoadGeometryAndAttributesMessageFrame.class, name = "43"),
		@JsonSubTypes.Type(value = j2735.PersonalSafetyMessage2.PersonalSafetyMessage2MessageFrame.class, name = "44"),
		@JsonSubTypes.Type(value = j2735.TrafficSignalPhaseAndTiming.TrafficSignalPhaseAndTimingMessageFrame.class, name = "45"),
		@JsonSubTypes.Type(value = j2735.SignalControlAndPrioritizationRequest.SignalControlAndPrioritizationRequestMessageFrame.class, name = "46"),
		@JsonSubTypes.Type(value = j2735.SignalControlAndPrioritizationStatus.SignalControlAndPrioritizationStatusMessageFrame.class, name = "47"),
		@JsonSubTypes.Type(value = j2735.RoadUserChargingConfigMessage.RoadUserChargingConfigMessageMessageFrame.class, name = "48"),
		@JsonSubTypes.Type(value = j2735.RoadUserChargingReportMessage.RoadUserChargingReportMessageMessageFrame.class, name = "49"),
		@JsonSubTypes.Type(value = j2735.TrafficLightStatusMessage.TrafficLightStatusMessageMessageFrame.class, name = "50"),
		@JsonSubTypes.Type(value = j2735.TestMessage00.TestMessage00MessageFrame.class, name = "240"),
		@JsonSubTypes.Type(value = j2735.TestMessage01.TestMessage01MessageFrame.class, name = "241"),
		@JsonSubTypes.Type(value = j2735.TestMessage02.TestMessage02MessageFrame.class, name = "242"),
		@JsonSubTypes.Type(value = j2735.TestMessage03.TestMessage03MessageFrame.class, name = "243"),
		@JsonSubTypes.Type(value = j2735.TestMessage04.TestMessage04MessageFrame.class, name = "244"),
		@JsonSubTypes.Type(value = j2735.TestMessage05.TestMessage05MessageFrame.class, name = "245"),
		@JsonSubTypes.Type(value = j2735.TestMessage06.TestMessage06MessageFrame.class, name = "246"),
		@JsonSubTypes.Type(value = j2735.TestMessage07.TestMessage07MessageFrame.class, name = "247"),
		@JsonSubTypes.Type(value = j2735.TestMessage08.TestMessage08MessageFrame.class, name = "248"),
		@JsonSubTypes.Type(value = j2735.TestMessage09.TestMessage09MessageFrame.class, name = "249"),
		@JsonSubTypes.Type(value = j2735.TestMessage10.TestMessage10MessageFrame.class, name = "250"),
		@JsonSubTypes.Type(value = j2735.TestMessage11.TestMessage11MessageFrame.class, name = "251"),
		@JsonSubTypes.Type(value = j2735.TestMessage12.TestMessage12MessageFrame.class, name = "252"),
		@JsonSubTypes.Type(value = j2735.TestMessage13.TestMessage13MessageFrame.class, name = "253"),
		@JsonSubTypes.Type(value = j2735.TestMessage14.TestMessage14MessageFrame.class, name = "254"),
		@JsonSubTypes.Type(value = j2735.TestMessage15.TestMessage15MessageFrame.class, name = "255")})
@Asn1ParameterizedTypes(idProperty = "messageId", idType = IdType.INTEGER, valueProperty = "value", value = {
		@Asn1ParameterizedTypes.Type(value = j2735.BasicSafetyMessage.BasicSafetyMessageMessageFrame.class, intId = 20),
		@Asn1ParameterizedTypes.Type(value = j2735.MapData.MapDataMessageFrame.class, intId = 18),
		@Asn1ParameterizedTypes.Type(value = j2735.SPAT.SPATMessageFrame.class, intId = 19),
		@Asn1ParameterizedTypes.Type(value = j2735.CommonSafetyRequest.CommonSafetyRequestMessageFrame.class, intId = 21),
		@Asn1ParameterizedTypes.Type(value = j2735.EmergencyVehicleAlert.EmergencyVehicleAlertMessageFrame.class, intId = 22),
		@Asn1ParameterizedTypes.Type(value = j2735.IntersectionCollision.IntersectionCollisionMessageFrame.class, intId = 23),
		@Asn1ParameterizedTypes.Type(value = j2735.NMEAcorrections.NMEAcorrectionsMessageFrame.class, intId = 24),
		@Asn1ParameterizedTypes.Type(value = j2735.ProbeDataManagement.ProbeDataManagementMessageFrame.class, intId = 25),
		@Asn1ParameterizedTypes.Type(value = j2735.ProbeVehicleData.ProbeVehicleDataMessageFrame.class, intId = 26),
		@Asn1ParameterizedTypes.Type(value = j2735.RoadSideAlert.RoadSideAlertMessageFrame.class, intId = 27),
		@Asn1ParameterizedTypes.Type(value = j2735.RTCMcorrections.RTCMcorrectionsMessageFrame.class, intId = 28),
		@Asn1ParameterizedTypes.Type(value = j2735.SignalRequestMessage.SignalRequestMessageMessageFrame.class, intId = 29),
		@Asn1ParameterizedTypes.Type(value = j2735.SignalStatusMessage.SignalStatusMessageMessageFrame.class, intId = 30),
		@Asn1ParameterizedTypes.Type(value = j2735.TravelerInformation.TravelerInformationMessageFrame.class, intId = 31),
		@Asn1ParameterizedTypes.Type(value = j2735.PersonalSafetyMessage.PersonalSafetyMessageMessageFrame.class, intId = 32),
		@Asn1ParameterizedTypes.Type(value = j2735.RoadSafetyMessage.RoadSafetyMessageMessageFrame.class, intId = 33),
		@Asn1ParameterizedTypes.Type(value = j2735.RoadWeatherMessage.RoadWeatherMessageMessageFrame.class, intId = 34),
		@Asn1ParameterizedTypes.Type(value = j2735.ProbeDataConfig.ProbeDataConfigMessageMessageFrame.class, intId = 35),
		@Asn1ParameterizedTypes.Type(value = j2735.ProbeDataReport.ProbeDataReportMessageMessageFrame.class, intId = 36),
		@Asn1ParameterizedTypes.Type(value = j2735.TollAdvertisementMessage.TollAdvertisementMessageMessageFrame.class, intId = 37),
		@Asn1ParameterizedTypes.Type(value = j2735.TollUsageMessage.TollUsageMessageMessageFrame.class, intId = 38),
		@Asn1ParameterizedTypes.Type(value = j2735.TollUsageAckMessage.TollUsageAckMessageMessageFrame.class, intId = 39),
		@Asn1ParameterizedTypes.Type(value = j2735.CooperativeControlMessage.CooperativeControlMessageMessageFrame.class, intId = 40),
		@Asn1ParameterizedTypes.Type(value = j2735.SensorDataSharingMessage.SensorDataSharingMessageMessageFrame.class, intId = 41),
		@Asn1ParameterizedTypes.Type(value = j2735.ManeuverSharingAndCoordinatingMessage.ManeuverSharingAndCoordinatingMessageMessageFrame.class, intId = 42),
		@Asn1ParameterizedTypes.Type(value = j2735.RoadGeometryAndAttributes.RoadGeometryAndAttributesMessageFrame.class, intId = 43),
		@Asn1ParameterizedTypes.Type(value = j2735.PersonalSafetyMessage2.PersonalSafetyMessage2MessageFrame.class, intId = 44),
		@Asn1ParameterizedTypes.Type(value = j2735.TrafficSignalPhaseAndTiming.TrafficSignalPhaseAndTimingMessageFrame.class, intId = 45),
		@Asn1ParameterizedTypes.Type(value = j2735.SignalControlAndPrioritizationRequest.SignalControlAndPrioritizationRequestMessageFrame.class, intId = 46),
		@Asn1ParameterizedTypes.Type(value = j2735.SignalControlAndPrioritizationStatus.SignalControlAndPrioritizationStatusMessageFrame.class, intId = 47),
		@Asn1ParameterizedTypes.Type(value = j2735.RoadUserChargingConfigMessage.RoadUserChargingConfigMessageMessageFrame.class, intId = 48),
		@Asn1ParameterizedTypes.Type(value = j2735.RoadUserChargingReportMessage.RoadUserChargingReportMessageMessageFrame.class, intId = 49),
		@Asn1ParameterizedTypes.Type(value = j2735.TrafficLightStatusMessage.TrafficLightStatusMessageMessageFrame.class, intId = 50),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage00.TestMessage00MessageFrame.class, intId = 240),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage01.TestMessage01MessageFrame.class, intId = 241),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage02.TestMessage02MessageFrame.class, intId = 242),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage03.TestMessage03MessageFrame.class, intId = 243),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage04.TestMessage04MessageFrame.class, intId = 244),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage05.TestMessage05MessageFrame.class, intId = 245),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage06.TestMessage06MessageFrame.class, intId = 246),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage07.TestMessage07MessageFrame.class, intId = 247),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage08.TestMessage08MessageFrame.class, intId = 248),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage09.TestMessage09MessageFrame.class, intId = 249),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage10.TestMessage10MessageFrame.class, intId = 250),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage11.TestMessage11MessageFrame.class, intId = 251),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage12.TestMessage12MessageFrame.class, intId = 252),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage13.TestMessage13MessageFrame.class, intId = 253),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage14.TestMessage14MessageFrame.class, intId = 254),
		@Asn1ParameterizedTypes.Type(value = j2735.TestMessage15.TestMessage15MessageFrame.class, intId = 255)})
abstract public class MessageFrame<TValue> extends Asn1Sequence {

	@JsonIgnore
	final protected DSRCmsgID messageId;
	@JsonIgnore
	final protected String name;
	private TValue value;
	public final static String INFORMATION_OBJECT_CLASS = "MESSAGE_ID_AND_TYPE";

	public DSRCmsgID getMessageId() {
		return messageId;
	}

	public String getName() {
		return name;
	}

	@JsonProperty("messageId")
	public String getIdString() {
		return messageId.toString();
	}

	public TValue getValue() {
		return value;
	}

	public void setValue(TValue value) {
		this.value = value;
	}

	public MessageFrame(int id, String name) {
		super(true);
		var theId = new DSRCmsgID();
		theId.setValue(id);
		this.messageId = theId;
		this.name = name;
	}
}