/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.J2540ITIS;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.AbstractMap.SimpleEntry;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import us.dot.its.jpo.asn.runtime.types.Asn1Integer;

public class AlternateRoute extends Asn1Integer {

  private static final Map<String, Long> nameValueMap =
      Map.ofEntries(
          new SimpleEntry<>("detour-where-possible", 8449L),
          new SimpleEntry<>("no-detour-available", 8450L),
          new SimpleEntry<>("follow-signs", 8451L),
          new SimpleEntry<>("follow-detour-signs", 8452L),
          new SimpleEntry<>("follow-special-detour-markers", 8453L),
          new SimpleEntry<>("do-not-follow-detour-signs", 8454L),
          new SimpleEntry<>("detour-in-operation", 8455L),
          new SimpleEntry<>("follow-local-detour", 8456L),
          new SimpleEntry<>("compulsory-detour-in-operation", 8457L),
          new SimpleEntry<>("no-suitable-detour-available", 8458L),
          new SimpleEntry<>("detour-is-no-longer-recommended", 8459L),
          new SimpleEntry<>("local-drivers-are-recommended-to-avoid-the-area", 8460L),
          new SimpleEntry<>("trucks-are-recommended-to-avoid-the-area", 8461L),
          new SimpleEntry<>("consider-alternate-route", 8462L),
          new SimpleEntry<>("consider-alternate-parking", 8463L),
          new SimpleEntry<>("consider-alternate-destination", 8464L),
          new SimpleEntry<>("consider-alternate-area", 8465L),
          new SimpleEntry<>("snow-route", 8466L),
          new SimpleEntry<>("emergency-snow-route", 8467L),
          new SimpleEntry<>("evacuation-route", 8468L),
          new SimpleEntry<>("truck-route", 8469L),
          new SimpleEntry<>("hazardous-materials-route", 8470L),
          new SimpleEntry<>("detour", 8471L));
  private static final Map<Long, String> valueNameMap =
      nameValueMap.entrySet().stream()
          .collect(Collectors.toUnmodifiableMap(Map.Entry::getValue, Map.Entry::getKey));

  public AlternateRoute() {
    super(0L, 65535L);
  }

  @JsonCreator
  public AlternateRoute(long value) {
    this();
    this.value = value;
  }

  @Override
  public Optional<String> name() {
    return Optional.ofNullable(valueNameMap.get(value));
  }

  public static Optional<AlternateRoute> named(String name) {
    return Optional.ofNullable(nameValueMap.get(name)).map(AlternateRoute::new);
  }

  public static Set<String> names() {
    return nameValueMap.keySet();
  }

  public static Set<Long> namedValues() {
    return valueNameMap.keySet();
  }
}
