/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.J2540ITIS;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import us.dot.its.jpo.asn.runtime.types.Asn1Integer;

public class AssetStatus extends Asn1Integer {

  private static final NamedValues namedValues = new NamedValues();

  public AssetStatus() {
    super(0L, 65535L);
  }

  @JsonCreator
  public AssetStatus(long value) {
    this();
    this.value = value;
  }

  private static class NamedValues {
    private final Map<String, Long> nameMap;
    private final Map<Long, String> valueMap;

    public NamedValues() {
      var mapBuilder = new LinkedHashMap<String, Long>();
      mapBuilder.put("unknown-status", 10240L);
      mapBuilder.put("ready-for-use", 10241L);
      mapBuilder.put("working-normally", 10242L);
      mapBuilder.put("working-autonomously", 10243L);
      mapBuilder.put("working-incorrectly", 10244L);
      mapBuilder.put("not-working", 10245L);
      mapBuilder.put("normal-maintenance", 10246L);
      mapBuilder.put("in-route-to-use", 10247L);
      mapBuilder.put("returning-from-use", 10248L);
      mapBuilder.put("out-of-service", 10249L);
      mapBuilder.put("off-duty", 10250L);
      mapBuilder.put("on-patrol", 10251L);
      mapBuilder.put("on-call", 10252L);
      mapBuilder.put("on-break", 10253L);
      mapBuilder.put("mandatory-time-off", 10254L);
      mapBuilder.put("low-on-fuel", 10255L);
      mapBuilder.put("low-on-water", 10256L);
      mapBuilder.put("low-charge", 10257L);
      mapBuilder.put("missing", 10258L);
      nameMap = Collections.unmodifiableMap(mapBuilder);
      final var valueMapBuilder = new LinkedHashMap<Long, String>();
      mapBuilder.forEach((k, v) -> valueMapBuilder.put(v, k));
      valueMap = Collections.unmodifiableMap(valueMapBuilder);
    }
  }

  @Override
  public Optional<String> name() {
    return Optional.ofNullable(namedValues.valueMap.get(value));
  }

  public static Optional<AssetStatus> named(String name) {
    return Optional.ofNullable(namedValues.nameMap.get(name)).map(AssetStatus::new);
  }

  public static Set<String> names() {
    return namedValues.nameMap.keySet();
  }

  public static Set<Long> namedValues() {
    return namedValues.valueMap.keySet();
  }
}
