/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.J2540ITIS;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import us.dot.its.jpo.asn.runtime.types.Asn1Integer;

public class ResponderGroupAffected extends Asn1Integer {

  private static final NamedValues namedValues = new NamedValues();

  public ResponderGroupAffected() {
    super(0L, 65535L);
  }

  @JsonCreator
  public ResponderGroupAffected(long value) {
    this();
    this.value = value;
  }

  private static class NamedValues {
    private final Map<String, Long> nameMap;
    private final Map<Long, String> valueMap;

    public NamedValues() {
      var mapBuilder = new LinkedHashMap<String, Long>();
      mapBuilder.put("emergency-vehicle-units", 9729L);
      mapBuilder.put("federal-law-enforcement-units", 9730L);
      mapBuilder.put("state-police-units", 9731L);
      mapBuilder.put("county-police-units", 9732L);
      mapBuilder.put("local-police-units", 9733L);
      mapBuilder.put("ambulance-units", 9734L);
      mapBuilder.put("rescue-units", 9735L);
      mapBuilder.put("fire-units", 9736L);
      mapBuilder.put("hAZMAT-units", 9737L);
      mapBuilder.put("light-tow-unit", 9738L);
      mapBuilder.put("heavy-tow-unit", 9739L);
      mapBuilder.put("private-tow-units", 9743L);
      mapBuilder.put("freeway-service-patrols", 9740L);
      mapBuilder.put("transportation-response-units", 9741L);
      mapBuilder.put("private-contractor-response-units", 9742L);
      nameMap = Collections.unmodifiableMap(mapBuilder);
      final var valueMapBuilder = new LinkedHashMap<Long, String>();
      mapBuilder.forEach((k, v) -> valueMapBuilder.put(v, k));
      valueMap = Collections.unmodifiableMap(valueMapBuilder);
    }
  }

  @Override
  public Optional<String> name() {
    return Optional.ofNullable(namedValues.valueMap.get(value));
  }

  public static Optional<ResponderGroupAffected> named(String name) {
    return Optional.ofNullable(namedValues.nameMap.get(name)).map(ResponderGroupAffected::new);
  }

  public static Set<String> names() {
    return namedValues.nameMap.keySet();
  }

  public static Set<Long> namedValues() {
    return namedValues.valueMap.keySet();
  }
}
