/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.J2540ITIS;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import us.dot.its.jpo.asn.runtime.types.Asn1Integer;

public class Structures extends Asn1Integer {

  private static final NamedValues namedValues = new NamedValues();

  public Structures() {
    super(0L, 65535L);
  }

  @JsonCreator
  public Structures(long value) {
    this();
    this.value = value;
  }

  private static class NamedValues {
    private final Map<String, Long> nameMap;
    private final Map<Long, String> valueMap;

    public NamedValues() {
      var mapBuilder = new LinkedHashMap<String, Long>();
      mapBuilder.put("rest-room", 13057L);
      mapBuilder.put("mens-rest-room", 13058L);
      mapBuilder.put("womens-rest-room", 13059L);
      mapBuilder.put("family-rest-room", 13060L);
      mapBuilder.put("dam", 13061L);
      mapBuilder.put("fish-hatchery", 13062L);
      mapBuilder.put("information", 13063L);
      mapBuilder.put("lighthouse", 13064L);
      mapBuilder.put("lookout-tower", 13065L);
      mapBuilder.put("ranger-station", 13066L);
      mapBuilder.put("grocery-store", 13068L);
      mapBuilder.put("lodging", 13069L);
      mapBuilder.put("post-office", 13070L);
      mapBuilder.put("picnic-shelter", 13072L);
      mapBuilder.put("group-camping", 13073L);
      mapBuilder.put("group-picnicking", 13074L);
      mapBuilder.put("n24-hour-pharmacy", 13075L);
      mapBuilder.put("kennel", 13076L);
      mapBuilder.put("laundry-facilities", 13077L);
      mapBuilder.put("shower-facilities", 13078L);
      mapBuilder.put("amphitheater", 13079L);
      mapBuilder.put("stable", 13080L);
      mapBuilder.put("hospital", 13081L);
      mapBuilder.put("emergency-medical-service-point", 13082L);
      mapBuilder.put("library", 13083L);
      mapBuilder.put("recycling-collection-center", 13084L);
      mapBuilder.put("school", 13085L);
      nameMap = Collections.unmodifiableMap(mapBuilder);
      final var valueMapBuilder = new LinkedHashMap<Long, String>();
      mapBuilder.forEach((k, v) -> valueMapBuilder.put(v, k));
      valueMap = Collections.unmodifiableMap(valueMapBuilder);
    }
  }

  @Override
  public Optional<String> name() {
    return Optional.ofNullable(namedValues.valueMap.get(value));
  }

  public static Optional<Structures> named(String name) {
    return Optional.ofNullable(namedValues.nameMap.get(name)).map(Structures::new);
  }

  public static Set<String> names() {
    return namedValues.nameMap.keySet();
  }

  public static Set<Long> namedValues() {
    return namedValues.valueMap.keySet();
  }
}
