/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.ProbeDataReport;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Choice;
import us.dot.its.jpo.asn.runtime.types.Asn1Integer;
import us.dot.its.jpo.asn.runtime.types.Asn1Null;
import us.dot.its.jpo.asn.runtime.types.Asn1OctetString;

@ToString(callSuper = true)
@Getter
@Setter
@JsonInclude(Include.NON_NULL)
public class RptCommSysPerfEvents extends Asn1Choice {

  @Asn1Property(tag = 0, name = "j2945-1ChanBusy")
  @JsonProperty("j2945-1ChanBusy")
  private Asn1Null j2945_1ChanBusy;

  @Asn1Property(tag = 1, name = "rfDataRsuInfo")
  @JsonProperty("rfDataRsuInfo")
  private RfDataRsuInfoOctetString rfDataRsuInfo;

  @Asn1Property(tag = 2, name = "numOfRsusObserved")
  @JsonProperty("numOfRsusObserved")
  private NumOfRsusObservedInteger numOfRsusObserved;

  @Asn1Property(tag = 3, name = "rfV2xJamDetect")
  @JsonProperty("rfV2xJamDetect")
  private Asn1Null rfV2xJamDetect;

  @Asn1Property(tag = 4, name = "j2945-1VehDens")
  @JsonProperty("j2945-1VehDens")
  private Asn1Null j2945_1VehDens;

  @Asn1Property(tag = 5, name = "j2945-1CqiBelow")
  @JsonProperty("j2945-1CqiBelow")
  private Asn1Null j2945_1CqiBelow;

  @Asn1Property(tag = 6, name = "j2945-1TrackingError")
  @JsonProperty("j2945-1TrackingError")
  private Asn1Null j2945_1TrackingError;

  @Asn1Property(tag = 7, name = "gnssHdopExceeds")
  @JsonProperty("gnssHdopExceeds")
  private Asn1Null gnssHdopExceeds;

  @Asn1Property(tag = 8, name = "gnssErrElipse")
  @JsonProperty("gnssErrElipse")
  private Asn1Null gnssErrElipse;

  @Asn1Property(tag = 9, name = "gnssSatsBelow")
  @JsonProperty("gnssSatsBelow")
  private Asn1Null gnssSatsBelow;

  @Asn1Property(tag = 10, name = "jammingDetect")
  @JsonProperty("jammingDetect")
  private Asn1Null jammingDetect;

  public RptCommSysPerfEvents() {}

  @Override
  public boolean hasExtensionMarker() {
    return true;
  }

  public static class RfDataRsuInfoOctetString extends Asn1OctetString {
    public RfDataRsuInfoOctetString() {
      super(6, 6);
    }

    @JsonCreator
    public RfDataRsuInfoOctetString(String value) {
      this();
      setValue(value);
    }
  }

  public static class NumOfRsusObservedInteger extends Asn1Integer {
    public NumOfRsusObservedInteger() {
      super(1L, 255L);
    }

    @JsonCreator
    public NumOfRsusObservedInteger(long value) {
      this();
      this.setValue(value);
    }
  }
}
