/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.ProbeDataReport;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import us.dot.its.jpo.asn.j2735.r2024.Common.Position3D;
import us.dot.its.jpo.asn.j2735.r2024.Common.PositionalAccuracy;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Integer;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@ToString(callSuper = true)
@Getter
@Setter
public class RptLocOfStops extends Asn1Sequence {

  @Asn1Property(tag = 0, name = "locationOfStop")
  @JsonProperty("locationOfStop")
  private Position3D locationOfStop;

  @Asn1Property(tag = 1, name = "locAccOfStop")
  @JsonProperty("locAccOfStop")
  private PositionalAccuracy locAccOfStop;

  @Asn1Property(tag = 2, name = "durationOfStop")
  @JsonProperty("durationOfStop")
  private DurationOfStopInteger durationOfStop;

  public static class DurationOfStopInteger extends Asn1Integer {
    public DurationOfStopInteger() {
      super(1L, 36000L);
    }

    @JsonCreator
    public DurationOfStopInteger(long value) {
      this();
      this.setValue(value);
    }
  }

  public RptLocOfStops() {}

  @Override
  public boolean hasExtensionMarker() {
    return true;
  }
}
