/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.ProbeVehicleData;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.Common.SpeedandHeadingandThrottleConfidence;
import j2735.Common.TimeConfidence;
import j2735.Common.PositionConfidenceSet;
import j2735.Common.HeadingConfidence;
import j2735.Common.ThrottleConfidence;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class ConfidenceSet extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "accelConfidence", optional = true)
	@JsonProperty("accelConfidence")
	private AccelSteerYawRateConfidence accelConfidence;
	@Asn1Property(tag = 1, name = "speedConfidence", optional = true)
	@JsonProperty("speedConfidence")
	private SpeedandHeadingandThrottleConfidence speedConfidence;
	@Asn1Property(tag = 2, name = "timeConfidence", optional = true)
	@JsonProperty("timeConfidence")
	private TimeConfidence timeConfidence;
	@Asn1Property(tag = 3, name = "posConfidence", optional = true)
	@JsonProperty("posConfidence")
	private PositionConfidenceSet posConfidence;
	@Asn1Property(tag = 4, name = "steerConfidence", optional = true)
	@JsonProperty("steerConfidence")
	private SteeringWheelAngleConfidence steerConfidence;
	@Asn1Property(tag = 5, name = "headingConfidence", optional = true)
	@JsonProperty("headingConfidence")
	private HeadingConfidence headingConfidence;
	@Asn1Property(tag = 6, name = "throttleConfidence", optional = true)
	@JsonProperty("throttleConfidence")
	private ThrottleConfidence throttleConfidence;

	public ConfidenceSet() {
		super(true);
	}
}