/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.ProbeVehicleData;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import j2735.Common.DescriptiveName;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import asn2pojo.runtime.types.IA5String;
import j2735.Common.VehicleID;
import j2735.Common.VehicleType;
import j2735.ITIS.VehicleGroupAffected;
import j2735.ITIS.ResponderGroupAffected;
import j2735.ITIS.IncidentResponseEquipment;
import asn2pojo.runtime.types.Asn1Choice;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class VehicleIdent extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "name", optional = true)
	@JsonProperty("name")
	private DescriptiveName name;
	@Asn1Property(tag = 1, name = "vin", optional = true)
	@JsonProperty("vin")
	private VINstring vin;
	@Asn1Property(tag = 2, name = "ownerCode", optional = true)
	@JsonProperty("ownerCode")
	private IA5String ownerCode;
	@Asn1Property(tag = 3, name = "id", optional = true)
	@JsonProperty("id")
	private VehicleID id;
	@Asn1Property(tag = 4, name = "vehicleType", optional = true)
	@JsonProperty("vehicleType")
	private VehicleType vehicleType;
	@Asn1Property(tag = 5, name = "vehicleClass", optional = true)
	@JsonProperty("vehicleClass")
	private VehicleClassChoice vehicleClass;

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class VehicleClassChoice extends Asn1Choice {
		@Asn1Property(tag = 0, name = "vGroup")
		@JsonProperty("vGroup")
		private VehicleGroupAffected vGroup;
		@Asn1Property(tag = 1, name = "rGroup")
		@JsonProperty("rGroup")
		private ResponderGroupAffected rGroup;
		@Asn1Property(tag = 2, name = "rEquip")
		@JsonProperty("rEquip")
		private IncidentResponseEquipment rEquip;

		public VehicleClassChoice() {
			super(false);
		}
	}

	public VehicleIdent() {
		super(true);
	}
}