/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.SensorDataSharingMessage;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import us.dot.its.jpo.asn.j2735.r2024.Common.DDateTime;
import us.dot.its.jpo.asn.j2735.r2024.Common.ElevationConfidence;
import us.dot.its.jpo.asn.j2735.r2024.Common.MsgCount;
import us.dot.its.jpo.asn.j2735.r2024.Common.Position3D;
import us.dot.its.jpo.asn.j2735.r2024.Common.PositionalAccuracy;
import us.dot.its.jpo.asn.j2735.r2024.Common.TemporaryID;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@ToString(callSuper = true)
@Getter
@Setter
public class SensorDataSharingMessage extends Asn1Sequence {

  @Asn1Property(tag = 0, name = "msgCnt")
  @JsonProperty("msgCnt")
  private MsgCount msgCnt;

  @Asn1Property(tag = 1, name = "sourceID")
  @JsonProperty("sourceID")
  private TemporaryID sourceID;

  @Asn1Property(tag = 2, name = "equipmentType")
  @JsonProperty("equipmentType")
  private EquipmentType equipmentType;

  @Asn1Property(tag = 3, name = "sDSMTimeStamp")
  @JsonProperty("sDSMTimeStamp")
  private DDateTime sDSMTimeStamp;

  @Asn1Property(tag = 4, name = "refPos")
  @JsonProperty("refPos")
  private Position3D refPos;

  @Asn1Property(tag = 5, name = "refPosXYConf")
  @JsonProperty("refPosXYConf")
  private PositionalAccuracy refPosXYConf;

  @Asn1Property(tag = 6, name = "refPosElConf", optional = true)
  @JsonProperty("refPosElConf")
  private ElevationConfidence refPosElConf;

  @Asn1Property(tag = 7, name = "objects")
  @JsonProperty("objects")
  @JacksonXmlElementWrapper(localName = "objects")
  @JacksonXmlProperty(localName = "DetectedObjectData")
  private DetectedObjectList objects;

  public SensorDataSharingMessage() {}
}
