/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.BasicSafetyMessage;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import us.dot.its.jpo.asn.runtime.serialization.BooleanDeserializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Boolean;

@JsonDeserialize(using = PivotingAllowed.PivotingAllowedDeserializer.class)
public class PivotingAllowed extends Asn1Boolean {

  public static class PivotingAllowedDeserializer extends BooleanDeserializer<PivotingAllowed> {
    public PivotingAllowedDeserializer() {
      super(PivotingAllowed.class);
    }

    @Override
    protected PivotingAllowed construct() {
      return new PivotingAllowed();
    }
  }
}
