/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.RoadWeatherMessage;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class NtcipPavementTreatment extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "latitude")
	@JsonProperty("latitude")
	private NTCIPEssPavementTreatmentLatitude latitude;
	@Asn1Property(tag = 1, name = "longitude")
	@JsonProperty("longitude")
	private NTCIPEssPavementTreatmentLongitude longitude;
	@Asn1Property(tag = 2, name = "location")
	@JsonProperty("location")
	private NTCIPEssPavementTreatmentLocation location;
	@Asn1Property(tag = 3, name = "productType", optional = true)
	@JsonProperty("productType")
	private NTCIPEssPaveTreatProductType productType;
	@Asn1Property(tag = 4, name = "form", optional = true)
	@JsonProperty("form")
	private NTCIPEssPaveTreatProductForm form;
	@Asn1Property(tag = 5, name = "percentage", optional = true)
	@JsonProperty("percentage")
	private NTCIPEssPercentProductMix percentage;
	@Asn1Property(tag = 6, name = "amount", optional = true)
	@JsonProperty("amount")
	private NTCIPEssPaveTreatmentAmount amount;
	@Asn1Property(tag = 7, name = "width", optional = true)
	@JsonProperty("width")
	private NTCIPEssPaveTreatmentWidth width;

	public NtcipPavementTreatment() {
		super(true);
	}
}