/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.Common;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;

@Getter
@JsonSerialize(using = RequestImportanceLevelSerializer.class)
@JsonDeserialize(using = RequestImportanceLevelDeserializer.class)
public enum RequestImportanceLevel implements Asn1Enumerated {
	REQUESTIMPORTANCELEVELUNKNOWN(0, "requestImportanceLevelUnKnown"), REQUESTIMPORTANCELEVEL1(1,
			"requestImportanceLevel1"), REQUESTIMPORTANCELEVEL2(2, "requestImportanceLevel2"), REQUESTIMPORTANCELEVEL3(
					3, "requestImportanceLevel3"), REQUESTIMPORTANCELEVEL4(4,
							"requestImportanceLevel4"), REQUESTIMPORTANCELEVEL5(5,
									"requestImportanceLevel5"), REQUESTIMPORTANCELEVEL6(6,
											"requestImportanceLevel6"), REQUESTIMPORTANCELEVEL7(7,
													"requestImportanceLevel7"), REQUESTIMPORTANCELEVEL8(8,
															"requestImportanceLevel8"), REQUESTIMPORTANCELEVEL9(9,
																	"requestImportanceLevel9"), REQUESTIMPORTANCELEVEL10(
																			10,
																			"requestImportanceLevel10"), REQUESTIMPORTANCELEVEL11(
																					11,
																					"requestImportanceLevel11"), REQUESTIMPORTANCELEVEL12(
																							12,
																							"requestImportanceLevel12"), REQUESTIMPORTANCELEVEL13(
																									13,
																									"requestImportanceLevel13"), REQUESTIMPORTANCELEVEL14(
																											14,
																											"requestImportanceLevel14"), REQUESTIMPORTANCERESERVED(
																													15,
																													"requestImportanceReserved");

	private final int index;
	private final String name;

	private RequestImportanceLevel(int index, String name) {
		this.index = index;
		this.name = name;
	}
}