/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.Common;

import lombok.Getter;
import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@Getter
@JsonSerialize(using = SpeedConfidenceSerializer.class)
@JsonDeserialize(using = SpeedConfidenceDeserializer.class)
public enum SpeedConfidence implements Asn1Enumerated {
	UNAVAILABLE(0, "unavailable"), PREC100MS(1, "prec100ms"), PREC10MS(2, "prec10ms"), PREC5MS(3, "prec5ms"), PREC1MS(4,
			"prec1ms"), PREC0_1MS(5, "prec0-1ms"), PREC0_05MS(6, "prec0-05ms"), PREC0_01MS(7, "prec0-01ms");

	private final int index;
	private final String name;

	public boolean hasExtensionMarker() {
		return false;
	}

	private SpeedConfidence(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}