/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.Common;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(using = VertOffset_B08.VertOffset_B08Deserializer.class)
public class VertOffset_B08 extends Asn1Integer {

	public VertOffset_B08() {
		super(-128L, 127L);
	}

	@JsonCreator
	public VertOffset_B08(long value) {
		this();
		this.value = value;
	}

	public static class VertOffset_B08Deserializer extends IntegerDeserializer<VertOffset_B08> {
		public VertOffset_B08Deserializer() {
			super(VertOffset_B08.class);
		}

		@Override
		protected VertOffset_B08 construct() {
			return new VertOffset_B08();
		}
	}
}