/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.TollUsageMessage;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import us.dot.its.jpo.asn.j2735.r2024.EfcDataDictionary.UserId;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1OctetString;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;
import us.dot.its.jpo.asn.runtime.types.IA5String;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@ToString(callSuper = true)
@Getter
@Setter
public class VehicleId extends Asn1Sequence {

  @Asn1Property(tag = 0, name = "vehicleIdentity", optional = true)
  @JsonProperty("vehicleIdentity")
  private VehicleIdentityOctetString vehicleIdentity;

  @Asn1Property(tag = 1, name = "licPlateState", optional = true)
  @JsonProperty("licPlateState")
  private IA5String licPlateState;

  @Asn1Property(tag = 2, name = "licPlateNumVeh", optional = true)
  @JsonProperty("licPlateNumVeh")
  private IA5String licPlateNumVeh;

  @Asn1Property(tag = 3, name = "licPlateNumTrailer", optional = true)
  @JsonProperty("licPlateNumTrailer")
  private IA5String licPlateNumTrailer;

  @Asn1Property(tag = 4, name = "userId", optional = true)
  @JsonProperty("userId")
  private UserId userId;

  public static class VehicleIdentityOctetString extends Asn1OctetString {
    public VehicleIdentityOctetString() {
      super(16, 16);
    }

    @JsonCreator
    public VehicleIdentityOctetString(String value) {
      this();
      setValue(value);
    }
  }

  public VehicleId() {}

  @Override
  public boolean hasExtensionMarker() {
    return true;
  }
}
