/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.RTCMcorrections;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedSerializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Enumerated;

@Getter
@JsonSerialize(using = RTCM_Revision.RTCM_RevisionSerializer.class)
@JsonDeserialize(using = RTCM_Revision.RTCM_RevisionDeserializer.class)
public enum RTCM_Revision implements Asn1Enumerated {
	UNKNOWN(0, "unknown"), RTCMREV2(1, "rtcmRev2"), RTCMREV3(2, "rtcmRev3"), RESERVED(3, "reserved");

	private final int index;
	private final String name;

	private RTCM_Revision(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public static class RTCM_RevisionSerializer extends EnumeratedSerializer<RTCM_Revision> {
		public RTCM_RevisionSerializer() {
			super(RTCM_Revision.class);
		}
	}

	public static class RTCM_RevisionDeserializer extends EnumeratedDeserializer<RTCM_Revision> {
		public RTCM_RevisionDeserializer() {
			super(RTCM_Revision.class);
		}

		@Override
		protected RTCM_Revision[] listEnumValues() {
			return RTCM_Revision.values();
		}
	}
}