/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.EmergencyVehicleAlert;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import j2735.Common.MinuteOfTheYear;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.Common.TemporaryID;
import j2735.RoadSideAlert.RoadSideAlert;
import j2735.Common.ResponseType;
import j2735.Common.EmergencyDetails;
import j2735.Common.VehicleMass;
import j2735.Common.VehicleType;
import j2735.ITIS.VehicleGroupAffected;
import j2735.ITIS.IncidentResponseEquipment;
import j2735.ITIS.ResponderGroupAffected;
import j2735.REGION.Reg_EmergencyVehicleAlert;
import asn2pojo.runtime.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class EmergencyVehicleAlert extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "timeStamp", optional = true)
	@JsonProperty("timeStamp")
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 1, name = "id", optional = true)
	@JsonProperty("id")
	private TemporaryID id;
	@Asn1Property(tag = 2, name = "rsaMsg")
	@JsonProperty("rsaMsg")
	private RoadSideAlert rsaMsg;
	@Asn1Property(tag = 3, name = "responseType", optional = true)
	@JsonProperty("responseType")
	private ResponseType responseType;
	@Asn1Property(tag = 4, name = "details", optional = true)
	@JsonProperty("details")
	private EmergencyDetails details;
	@Asn1Property(tag = 5, name = "mass", optional = true)
	@JsonProperty("mass")
	private VehicleMass mass;
	@Asn1Property(tag = 6, name = "basicType", optional = true)
	@JsonProperty("basicType")
	private VehicleType basicType;
	@Asn1Property(tag = 7, name = "vehicleType", optional = true)
	@JsonProperty("vehicleType")
	private VehicleGroupAffected vehicleType;
	@Asn1Property(tag = 8, name = "responseEquip", optional = true)
	@JsonProperty("responseEquip")
	private IncidentResponseEquipment responseEquip;
	@Asn1Property(tag = 9, name = "responderType", optional = true)
	@JsonProperty("responderType")
	private ResponderGroupAffected responderType;
	@Asn1Property(tag = 10, name = "regional", optional = true)
	@JsonProperty("regional")
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_EmergencyVehicleAlert> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_EmergencyVehicleAlert.class, 1L, 4L);
		}
	}

	EmergencyVehicleAlert() {
		super(true);
	}
}