/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.ProbeVehicleData;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedDeserializer;
import us.dot.its.jpo.asn.runtime.serialization.EnumeratedSerializer;
import us.dot.its.jpo.asn.runtime.types.Asn1Enumerated;

@Getter
@JsonSerialize(using = YawRateConfidence.YawRateConfidenceSerializer.class)
@JsonDeserialize(using = YawRateConfidence.YawRateConfidenceDeserializer.class)
public enum YawRateConfidence implements Asn1Enumerated {
  UNAVAILABLE(0, "unavailable"),
  DEGSEC_100_00(1, "degSec-100-00"),
  DEGSEC_010_00(2, "degSec-010-00"),
  DEGSEC_005_00(3, "degSec-005-00"),
  DEGSEC_001_00(4, "degSec-001-00"),
  DEGSEC_000_10(5, "degSec-000-10"),
  DEGSEC_000_05(6, "degSec-000-05"),
  DEGSEC_000_01(7, "degSec-000-01");

  private final int index;
  private final String name;

  private YawRateConfidence(int index, String name) {
    this.index = index;
    this.name = name;
  }

  public static class YawRateConfidenceSerializer extends EnumeratedSerializer<YawRateConfidence> {
    public YawRateConfidenceSerializer() {
      super(YawRateConfidence.class);
    }
  }

  public static class YawRateConfidenceDeserializer
      extends EnumeratedDeserializer<YawRateConfidence> {
    public YawRateConfidenceDeserializer() {
      super(YawRateConfidence.class);
    }

    @Override
    protected YawRateConfidence[] listEnumValues() {
      return YawRateConfidence.values();
    }
  }
}
