/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.ProbeDataReport;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.JsonDeserializer.None;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import j2735.MessageFrame.MessageFrame;

@JsonRootName("MessageFrame")
@JsonDeserialize(using = None.class)
public class ProbeDataReportMessageMessageFrame extends MessageFrame<ProbeDataReportMessage> {

	public ProbeDataReportMessageMessageFrame() {
		super(36, "ProbeDataReportMessage");
	}

	@Override
	@JsonSerialize(using = ProbeDataReportMessageMessageFrameValueSerializer.class)
	public ProbeDataReportMessage getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = ProbeDataReportMessageMessageFrameValueDeserializer.class)
	public void setValue(ProbeDataReportMessage value) {
		super.setValue(value);
	}
}