/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.ProbeDataReport;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class RptIntervalEvents extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "wiperStatus", optional = true)
	@JsonProperty("wiperStatus")
	private RptWiperStatus wiperStatus;
	@Asn1Property(tag = 1, name = "vehCount", optional = true)
	@JsonProperty("vehCount")
	private VehCountInteger vehCount;
	@Asn1Property(tag = 2, name = "weatherData", optional = true)
	@JsonProperty("weatherData")
	@JacksonXmlElementWrapper(localName = "weatherData")
	@JacksonXmlProperty(localName = "NtcipEssData")
	private RptVehicleReport weatherData;
	@Asn1Property(tag = 3, name = "transitVehData", optional = true)
	@JsonProperty("transitVehData")
	private RptTransitVehData transitVehData;
	@Asn1Property(tag = 4, name = "numOfOccupants", optional = true)
	@JsonProperty("numOfOccupants")
	private NumOfOccupantsInteger numOfOccupants;

	public static class VehCountInteger extends Asn1Integer {
		public VehCountInteger() {
			super(0L, 10000L);
		}

		@JsonCreator
		public VehCountInteger(long value) {
			this();
			this.value = value;
		}
	}

	public static class NumOfOccupantsInteger extends Asn1Integer {
		public NumOfOccupantsInteger() {
			super(0L, 255L);
		}

		@JsonCreator
		public NumOfOccupantsInteger(long value) {
			this();
			this.value = value;
		}
	}

	public RptIntervalEvents() {
		super(true);
	}
}