/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.TravelerInformation;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import j2735.Common.HeadingSlice;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.Common.Extent;
import j2735.Common.LaneWidth;
import j2735.REGION.Reg_GeometricProjection;
import asn2pojo.runtime.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class GeometricProjection extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "direction")
	@JsonProperty("direction")
	private HeadingSlice direction;
	@Asn1Property(tag = 1, name = "extent", optional = true)
	@JsonProperty("extent")
	private Extent extent;
	@Asn1Property(tag = 2, name = "laneWidth", optional = true)
	@JsonProperty("laneWidth")
	private LaneWidth laneWidth;
	@Asn1Property(tag = 3, name = "circle")
	@JsonProperty("circle")
	private Circle circle;
	@Asn1Property(tag = 4, name = "regional", optional = true)
	@JsonProperty("regional")
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_GeometricProjection> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_GeometricProjection.class, 1L, 4L);
		}
	}

	GeometricProjection() {
		super(true);
	}
}