//
// **MANUAL EDIT**
//
// Fix usCanMexState is IA5String property with extensible length constraint:
// IA5String (SIZE(2,...))
//
// Use fixed SIZE(2) for practical purposes since no extensions are present
//
/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.RoadUserChargingConfigMessage;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Sequence;
import us.dot.its.jpo.asn.runtime.types.IA5String;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@ToString(callSuper = true)
@Getter
@Setter
public class PrimaryRegionState extends Asn1Sequence {

  // EDITED
  @Asn1Property(tag = 0, name = "usCanMexState")
  @JsonProperty("usCanMexState")
  private UsCanMexState usCanMexState;

  // ADDED
  public static class UsCanMexState extends IA5String {

    public UsCanMexState() {
      super(2, 2);
    }

    @JsonCreator
    public UsCanMexState(String value) {
      this();
      this.value = value;
    }
  }

  @Asn1Property(tag = 1, name = "chargingFees", optional = true)
  @JsonProperty("chargingFees")
  private ChargingFees chargingFees;

  public PrimaryRegionState() {}

  @Override
  public boolean hasExtensionMarker() {
    return true;
  }
}
