/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.EfcDataDictionary;

import asn2pojo.runtime.serialization.IntegerDeserializer;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(using = LocalVehicleClassId.LocalVehicleClassIdDeserializer.class)
public class LocalVehicleClassId extends Int2Unsigned {

	public LocalVehicleClassId() {
		super();
	}

	@JsonCreator
	public LocalVehicleClassId(long value) {
		this();
		this.value = value;
	}

	public static class LocalVehicleClassIdDeserializer extends IntegerDeserializer<LocalVehicleClassId> {
		public LocalVehicleClassIdDeserializer() {
			super(LocalVehicleClassId.class);
		}

		@Override
		protected LocalVehicleClassId construct() {
			return new LocalVehicleClassId();
		}
	}
}