/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.RoadWeatherMessage;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class NtcipWind extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "avgSpeed", optional = true)
	@JsonProperty("avgSpeed")
	private NTCIPWindSensorAvgSpeed avgSpeed;
	@Asn1Property(tag = 1, name = "avgDirection", optional = true)
	@JsonProperty("avgDirection")
	private NTCIPWindSensorAvgDirection avgDirection;
	@Asn1Property(tag = 2, name = "currentSpeed", optional = true)
	@JsonProperty("currentSpeed")
	private NTCIPWindSensorSpotSpeed currentSpeed;
	@Asn1Property(tag = 3, name = "curDirection", optional = true)
	@JsonProperty("curDirection")
	private NTCIPWindSensorSpotDirection curDirection;
	@Asn1Property(tag = 4, name = "gustSpeed", optional = true)
	@JsonProperty("gustSpeed")
	private NTCIPWindSensorGustSpeed gustSpeed;
	@Asn1Property(tag = 5, name = "gustDirection", optional = true)
	@JsonProperty("gustDirection")
	private NTCIPWindSensorGustDirection gustDirection;

	public NtcipWind() {
		super(true);
	}
}