/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.RoadWeatherMessage;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class NtcipEssData extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "airTemp", optional = true)
	@JsonProperty("airTemp")
	private NtcipAirTemperature airTemp;
	@Asn1Property(tag = 1, name = "atmosphere", optional = true)
	@JsonProperty("atmosphere")
	private NtcipAtmosphericPressure atmosphere;
	@Asn1Property(tag = 2, name = "wind", optional = true)
	@JsonProperty("wind")
	private NtcipWind wind;
	@Asn1Property(tag = 3, name = "humidity", optional = true)
	@JsonProperty("humidity")
	private NtcipRelativeHumidity humidity;
	@Asn1Property(tag = 4, name = "dewpoint", optional = true)
	@JsonProperty("dewpoint")
	private NtcipDewPoint dewpoint;
	@Asn1Property(tag = 5, name = "pavement", optional = true)
	@JsonProperty("pavement")
	private NtcipPavement pavement;
	@Asn1Property(tag = 6, name = "visibility", optional = true)
	@JsonProperty("visibility")
	private NtcipVisibility visibility;
	@Asn1Property(tag = 7, name = "visSituation", optional = true)
	@JsonProperty("visSituation")
	private NtcipVisibilitySituation visSituation;
	@Asn1Property(tag = 8, name = "cloudSitiation", optional = true)
	@JsonProperty("cloudSitiation")
	private NtcipCloudSituation cloudSitiation;
	@Asn1Property(tag = 9, name = "precipitation", optional = true)
	@JsonProperty("precipitation")
	private NtcipPrecipitation precipitation;
	@Asn1Property(tag = 10, name = "solarRadiation", optional = true)
	@JsonProperty("solarRadiation")
	private NtcipSolarRadiation solarRadiation;

	public NtcipEssData() {
		super(true);
	}
}