/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package j2735.CommonSafetyRequest;

import lombok.Getter;
import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@Getter
@JsonSerialize(using = RequestedItemSerializer.class)
@JsonDeserialize(using = RequestedItemDeserializer.class)
public enum RequestedItem implements Asn1Enumerated {
	RESERVED(0, "reserved"), ITEMA(1, "itemA"), ITEMB(2, "itemB"), ITEMC(3, "itemC"), ITEMD(4, "itemD"), ITEME(5,
			"itemE"), ITEMF(6, "itemF"), ITEMG(7, "itemG"), ITEMI(8, "itemI"), ITEMJ(9,
					"itemJ"), ITEMK(10, "itemK"), ITEML(11, "itemL"), ITEMM(12,
							"itemM"), ITEMN(13, "itemN"), ITEMO(14, "itemO"), ITEMP(15, "itemP"), ITEMQ(16, "itemQ");

	private final int index;
	private final String name;

	public boolean hasExtensionMarker() {
		return false;
	}

	private RequestedItem(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 16;
	}
}