/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.asn.j2735.r2024.TollAdvertisementMessage;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.asn.runtime.annotations.Asn1Property;
import us.dot.its.jpo.asn.runtime.types.Asn1Choice;

@Getter
@Setter
@JsonInclude(Include.NON_NULL)
public class ChargesTable extends Asn1Choice {

	@Asn1Property(tag = 0, name = "vehTypeBased")
	@JsonProperty("vehTypeBased")
	@JacksonXmlElementWrapper(localName = "vehTypeBased")
	@JacksonXmlProperty(localName = "VehTypeCharges")
	private VehTypeChargesTable vehTypeBased;
	@Asn1Property(tag = 1, name = "numAxlesBased")
	@JsonProperty("numAxlesBased")
	@JacksonXmlElementWrapper(localName = "numAxlesBased")
	@JacksonXmlProperty(localName = "AxlesCharges")
	private AxlesChargesTable numAxlesBased;
	@Asn1Property(tag = 2, name = "weightBased")
	@JsonProperty("weightBased")
	@JsonSerialize(using = WeightChargesTable.WeightChargesTableSerializer.class)
	@JsonDeserialize(using = WeightChargesTable.WeightChargesTableDeserializer.class)
	private WeightChargesTable weightBased;

	public ChargesTable() {
		super(true);
	}
}